# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EvmCli < Formula
  desc ""
  homepage "https://github.com/idanya/homebrew-tools"
  version "1.0.5"

  on_macos do
    url "https://github.com/idanya/evm-cli/releases/download/v1.0.5/evm-cli_Darwin_x86_64.tar.gz"
    sha256 "5bc8538958a68b313885951e7ea746323cc5eb58c31403d611a11f14576dfff5"

    def install
      bin.install "evm-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the EvmCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/idanya/evm-cli/releases/download/v1.0.5/evm-cli_Linux_x86_64.tar.gz"
      sha256 "54223f7a27a9d3aeb441445e5d92df760462d8236937dab98eaa856a68bbc5dd"

      def install
        bin.install "evm-cli"
      end
    end
  end
end
