# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EvmCli < Formula
  desc ""
  homepage "https://github.com/idanya/homebrew-tools"
  version "1.0.7"

  on_macos do
    url "https://github.com/idanya/evm-cli/releases/download/v1.0.7/evm-cli_Darwin_x86_64.tar.gz"
    sha256 "e3faf022712f87e7d45375e80508a7c1c6985deec8ecb40ed626b09d82280b90"

    def install
      bin.install "evm-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the EvmCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/idanya/evm-cli/releases/download/v1.0.7/evm-cli_Linux_x86_64.tar.gz"
      sha256 "4d442e1e8da6e22eef29fe765d13ed1ee37eed62b6c19f3513dfe2d6e4e37de7"

      def install
        bin.install "evm-cli"
      end
    end
  end
end
